### ISSUE TITLE
Faker dependency

### ISSUE THREAD

**Issue by gberginc** [ManageIQ/manageiq-providers-lenovo#109]
The gemspec currently adds `faker` dependency which seems to be only used for specs, so I suggest to repace it with the `add_development_dependency`

https://github.com/ManageIQ/manageiq-providers-lenovo/blob/c6a84c3bcf249ef226e8a939aaea5816532345b1/manageiq-providers-lenovo.gemspec#L20

**Comment by saulotoledo** [comment]
https://github.com/ManageIQ/manageiq-providers-lenovo/pull/165 solves the issue.

**Comment by saulotoledo** [comment]
@gberginc, could you close this issue?

**Comment by gberginc** [comment]
Thanks @saulotoledo.
