### ISSUE TITLE
When asset_details are not returned, the asset_details object is nil...should be empty

### ISSUE THREAD

**Issue by rodneyhbrown7** [ManageIQ/manageiq-providers-lenovo#55]
In the physical_server refresher, we need to make sure that we are not returning nil for any high level attribute, this causes particular pain for the UI.

**Comment by walteraa** [comment]
@rodneyhbrown7 is it solved?

**Comment by rodneyhbrown7** [comment]
Yes @walteraa this is fixed.  Closing as addressed by https://github.com/ManageIQ/manageiq-providers-lenovo/pull/67
